#############################测试环境配置#######################

#DB配置
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: test
      password: BPuy3JpbN89KEwJ5VM/cmBq7j90BnH1LmmOedbVYRFx15HNDv4uwK2VIsFoxai1Sozj/6zWijg8wPX/uxJUd3Q==
      publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALSoCdb3ISKQnK0uPZD27IizS9GV1GD6uNr6F62rE8r+1l16SKH4bO93TLxUab4t2z07o4VucNVTrcIf+xwSO50CAwEAAQ==
      connection-properties: config.decrypt=true;config.decrypt.key=${spring.datasource.druid.publicKey}
      #配置初始化大小/最小/最大
      initial-size: 8
      min-idle: 8
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        config:
          enabled: true

redis:
  database:  0
  host:  192.168.0.1
  port:  6379
  password: test
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
    timeout: 0
#消息中间件rocketmq
apache:
  rocketmq:
    producer:
      groupName: springBootDemo
      topic: Demo
    consumer1:
      groupName: springBootDemo
      topic: Demo
    consumer2:
      groupName: springBootDemo
      topic: Demo

    namesrvAddr: 192.168.0.1:9876